# Generated by Django 3.1.4 on 2020-12-10 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codm', models.CharField(max_length=50, unique=True)),
                ('nro_lote', models.IntegerField()),
                ('observaciones', models.CharField(max_length=255)),
                ('nro_tarea', models.IntegerField()),
                ('nro_cuenta', models.IntegerField()),
                ('nya_cliente', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(default=None, max_length=20)),
                ('tel1', models.CharField(default=None, max_length=255)),
                ('tel2', models.CharField(default=None, max_length=255)),
                ('tel3', models.CharField(default=None, max_length=255)),
                ('tel4', models.CharField(default=None, max_length=255)),
                ('email', models.CharField(default=None, max_length=255)),
                ('recuperado', models.BooleanField(default=False)),
                ('base_nro_serie', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recupero.empresas')),
                ('localidad_contable', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='localidad_contable', to='recupero.localidades')),
                ('localidad_retiro', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='localidad_retiro', to='recupero.localidades')),
            ],
        ),
    ]
