# Generated by Django 3.1.4 on 2020-12-11 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codm_barras', models.CharField(default=None, max_length=50, unique=True)),
                ('codm', models.CharField(default=None, max_length=50, unique=True)),
                ('id_c', models.IntegerField(default=0)),
                ('nro_serie_barras', models.CharField(default=None, max_length=50, unique=True)),
                ('nro_serie', models.CharField(default=None, max_length=50, unique=True)),
                ('nro_tarea_barras', models.CharField(default=None, max_length=50, unique=True)),
                ('nro_tarea', models.IntegerField()),
                ('nro_cuenta', models.IntegerField()),
                ('nya_cliente', models.CharField(default=None, max_length=255)),
                ('id_actividad', models.CharField(default=None, max_length=50)),
                ('telefonos', models.CharField(default=None, max_length=500)),
                ('domicilio', models.CharField(default=None, max_length=500)),
                ('codigo_postal', models.CharField(default=None, max_length=20)),
                ('item_tarea', models.CharField(default=None, max_length=255)),
                ('fecha_envio', models.DateField(default=None)),
                ('fecha_creacion', models.DateField(default=None)),
                ('zona', models.CharField(default=None, max_length=255)),
                ('nombre_cartera', models.CharField(default=None, max_length=255)),
                ('notas', models.CharField(default=None, max_length=255)),
                ('correo', models.CharField(default=None, max_length=255)),
                ('email', models.CharField(default=None, max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recupero.empresas')),
                ('localidad', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='localidad', to='recupero.localidades')),
                ('localidad_contable', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='localidad_contable', to='recupero.localidades')),
            ],
        ),
    ]
