# Generated by Django 3.1.4 on 2020-12-14 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recupero', '0002_equipo_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoLlamada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(default=None, max_length=255)),
                ('n1', models.CharField(default=None, max_length=255)),
                ('n2', models.CharField(default=None, max_length=255)),
                ('n3', models.CharField(default=None, max_length=255)),
                ('n4', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Llamadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_llamada', models.DateField(default=None)),
                ('fecha_retiro', models.DateField(default=None)),
                ('hora_inicio_retiro', models.TimeField(default=None)),
                ('hora_fin_retiro', models.TimeField(default=None)),
                ('entre_calles', models.CharField(default=None, max_length=255)),
                ('observacion', models.CharField(default=None, max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recupero.equipo')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recupero.resultadollamada')),
            ],
        ),
    ]
