# Generated by Django 3.1.4 on 2020-12-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recupero', '0003_llamadas_resultadollamada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadollamada',
            name='n1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='resultadollamada',
            name='n2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='resultadollamada',
            name='n3',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='resultadollamada',
            name='n4',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
