# Generated by Django 3.1.4 on 2020-12-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recupero', '0004_auto_20201214_1805'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='resultadollamada',
            index_together={('n1', 'n2', 'n3', 'n4')},
        ),
    ]
