# Generated by Django 3.1.4 on 2020-12-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recupero', '0005_auto_20201214_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='codm',
            field=models.CharField(db_index=True, default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_creacion',
            field=models.DateField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_envio',
            field=models.DateField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nro_serie',
            field=models.CharField(db_index=True, default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='llamadas',
            name='fecha_llamada',
            field=models.DateField(db_index=True, default=None),
        ),
    ]
